$(document).on("pageInit","#page-pai_podcast-goods,#page-pai_user-goods", function(e, pageId, $page) {
    // 无限加载
    if(pageId == 'page-pai_podcast-goods' || pageId == 'page-pai_user-goods'){
		var loading = false, p = 1, page_ajax_url;
		$($page).on('infinite', function() {
	 	 	console.log(has_next);
			if (loading || !has_next){
				if (!has_next){
				 	// 加载完毕，则注销无限加载事件，以防不必要的加载
                  	$.detachInfiniteScroll($('.infinite-scroll'));
                  	// 提示无更多数据
		 	 		document.querySelector(".m-infinite-scroll-preloader").innerHTML = '<div style="text-align:center;font-size:0.75rem;color:#999;margin-bottom:10px;">无更多数据</div>';
		 	 	}
	 			return;
	 	 	} 
	 	 	
	      	loading = true;
	      	pageId == 'page-pai_podcast-goods' ? page_ajax_url = TMPL+'index.php?ctl=pai_podcast&act=goods&post_type=json&page_size=10' : page_ajax_url = TMPL+'index.php?ctl=pai_user&act=goods&post_type=json&page_size=10';
		  	var query = new Object();
		  	p = p + 1;
	      	$.ajax({
		      	url:page_ajax_url,
		      	dataType: "json",
		        data:{p:p},
		        async:false,
		        success:function(result){
		        	if(result.status == 1){
		        		console.log(result);
			        	has_next = result.data.page.has_next;
			        	var data_list = result.data.list, is_podcast = result.is_podcast, html, order_status, pay_status, btn_bar, btn;
						var source = '{{each list as list}}'
						+        		'<li class="card block-good-virtual">'
						+        			'<div class="card-header">'
						+        				'<div class="item-title">{{list.podcast_name}}</div>'
						+        				'<div class="item-after">'
						+        					'{{if list.status == 0}}'
						+        						'{{if list.pai_diamonds == list.last_pai_diamonds}}'
						+        							'<span class="pai_status_inline">领先</span>'
						+        						'{{else}}'
						+        							'<span class="pai_status_fail">落后</span>'
						+        						'{{/if}}'
						+        					'{{else if list.status == 1}}'
						+        						'{{if list.order_id > 0}}'
						+        							'{{if list.order_status == 1}}'
						+        								'<span class="pai_status_ing">等待买家付款</span>'
						+        							'{{else if list.order_status == 6}}'
						+        								'<span class="pai_status_fail">竞拍失败</span>'
						+        							'{{/if}}'
						+        						'{{else}}'
						+        							'{{if list.pai_status == 0}}'
						+        								'<span class="pai_status_out">出局</span>'
						+        							'{{else if list.pai_status == 2}}'
						+        								'<span class="pai_status_inline">排队中</span>'
						+        							'{{/if}}'
						+        						'{{/if}}'
						+        					'{{else if list.status == 2}}'
						+        						'<span class="pai_status_fail">竞拍失败</span>'
						+        					'{{else if list.status == 3}}'
						+        						'<span class="pai_status_fail">竞拍失败</span>'
						+        					'{{else if list.status == 4}}'
						+        						'{{if is_podcast}}'
						+        							'{{if list.order_status == 2}}'
						+        								'{{if list.expire_date_time > 0}}'
						+        									'<span class="pai_status_ing">等待完成约会</span>'
						+        								'{{else}}'
						+        									'<span class="pai_status_ing">已完成约会</span>'
						+        								'{{/if}}'
						+        							'{{else if list.order_status == 3}}'
						+        								'<span class="pai_status_ing">等待买家确认</span>'
						+        							'{{else if list.order_status == 4}}'
						+        								'<span class="pai_status_success">竞拍成功</span>'
						+        							'{{else if list.order_status == 5}}'
						+        								'<span class="pai_status_fail">退款</span>'
						+        							'{{/if}}'
						+        						'{{else}}'
						+        							'{{if list.order_status == 2}}'
						+        								'{{if list.expire_date_time > 0}}'
						+        									'<span class="pai_status_ing">等待完成约会</span>'
						+        								'{{else}}'
						+        									'<span class="pai_status_ing">等待主播确认</span>'
						+        								'{{/if}}'
						+        							'{{else if list.order_status == 3}}'
						+        								'<span class="pai_status_ing">已完成约会</span>'
						+        							'{{else if list.order_status == 4}}'
						+        								'<span class="pai_status_success">竞拍成功</span>'
						+        							'{{else if list.order_status == 5}}'
						+        								'<span class="pai_status_fail">退款</span>'
						+        							'{{else if list.order_status == 6}}'
						+        								'<span class="pai_status_fail">超时未付款</span>'
						+        							'{{else if list.order_status == 0}}'
						+        								'<span class="pai_status_fail">出局</span>'
						+        							'{{/if}}'
						+        						'{{/if}}'
						+        					'{{/if}}'
						+        				'</div>'
						+        			'</div>'
						+        			'<div class="card-content good_content">'
						+        				'<div class="list-block media-list">'
						+        					'<ul>'
						+        						'<li>'
						+        							'{{if list.status == 0 || list.status == 3}}'
						+        								'<a href="javascript:void(0);" class="item-content J-pai_live" data-id="{{list.id}}">'
						+        							'{{else}}'
						+        								'{{if list.order_sn}}'
						+        									'{{if is_podcast == 1}}'
						+        										'<a href="'+TMPL+'index.php?ctl=pai_podcast&act=order&order_sn={{list.order_sn}}&pai_id={{list.id}}" class="item-content" data-id="{{list.id}}">'
						+        									'{{else}}'
						+        										'<a href="'+TMPL+'index.php?ctl=pai_user&act=order&order_sn={{list.order_sn}}&pai_id={{list.id}}" class="item-content" data-id="{{list.id}}">'
						+        									'{{/if}}'
						+        								'{{else}}'
						+        									'<a href="javascript:void(0);" class="item-content J-pai_live" data-id="{{list.id}}">'
						+        								'{{/if}}'
						+        							'{{/if}}'
						+        								'<div class="item-media">'
						+        									'<img src="{{list.imgs[0]}}" width="80" height="70">'
						+        								'</div>'
						+        								'<div class="item-inner">'
						+        									'<div class="item-title-row">'
						+        										'<div class="item-title good_name">{{list.name}}</div>'
						+        									'</div>'
						+        									'<div class="item-subtitle f_999">最高价：<span class="diamond f_theme">{{list.last_pai_diamonds}}</span></div>'
						+        								'</div>'
						+        							'</a>'
						+        						'</li>'
						+        					'</ul>'
						+        				'</div>'
						+        			'</div>'
						+        			'<div class="card-footer">'
						+        				'<div class="list-block">'
						+        					'<ul>'
						+        						'{{if list.status == 0}}'
						+        							'<li class="item-content">'
						+        								'<div class="item-inner">'
						+        									'<div class="item-title f_999">我的出价</div>'
						+        									'<div class="item-after"><span class="diamond f_theme">{{list.pai_diamonds}}</span></div>'
						+        								'</div>'
						+        							'</li>'
						+        							'{{if list.order_id && list.order_status < 4}}'
						+        								'<li class="item-content">'
						+        									'<div class="item-inner">'
						+        										'<div class="item-title f_555 f12">'
						+        											'<span class="left_time" data-leftTime="{{list.pai_left_time}}"></span>&nbsp;结束'
						+        										'</div>'
						+        										'<div class="item-after">'
						+        											'{{if list.pai_diamonds == list.last_pai_diamonds}}'
						+        												'<a href="javascript:void(0);" class="button button-theme button-round button-fill J_join_live" data-id="{list.podcast_id}">查看竞拍</a>'
						+        											'{{else}}'
						+        												'<a href="javascript:void(0);" class="button button-theme button-round button-fill J_join_live" data-id="{list.podcast_id}">继续出价</a>'
						+        											'{{/if}}'
						+        										'</div>'
						+        									'</div>'
						+        								'</li>'
						+        							'{{/if}}'
						+        						'{{else if list.status == 1}}'
						+        							'<li class="item-content">'
						+        								'<div class="item-inner">'
						+        									'<div class="item-title f_999">'
						+        										'{{if is_podcast}}'
						+        											'{{if list.order_status == 1}}待收款{{else if list.order_status == 6}}已扣买家保证金{{/if}}'
						+        										'{{else}}'
						+        											'{{if list.order_id > 0}}'
						+        												'{{if list.order_status == 1}}待付款{{else if list.order_status == 6}}冻结保证金{{/if}}'
						+        											'{{else}}'
						+        												'我的出价'
						+        											'{{/if}}'
						+        										'{{/if}}'
						+        									'</div>'
						+        									'<div class="item-after"><span class="diamond f_theme">{{list.pai_diamonds}}</span></div>'
						+        								'</div>'
						+        							'</li>'
						+        							'{{if list.order_id && list.order_status < 4}}'
						+        								'<li class="item-content">'
						+        									'<div class="item-inner">'
						+        										'<div class="item-title f_555 f12">'
						+        											'<span class="left_time" data-leftTime="{{list.pai_left_time}}"></span>&nbsp;结束'
						+        										'</div>'
						+        										'<div class="item-after">'
						+        											'{{if list.pai_diamonds == list.last_pai_diamonds}}'
						+        												'<a href="javascript:void(0);" class="button button-theme button-round button-fill J_join_live" data-id="{list.podcast_id}">查看竞拍</a>'
						+        											'{{else}}'
						+        												'<a href="javascript:void(0);" class="button button-theme button-round button-fill J_join_live" data-id="{list.podcast_id}">继续出价</a>'
						+        											'{{/if}}'
						+        										'</div>'
						+        									'</div>'
						+        								'</li>'
						+        							'{{/if}}'
						+        						'{{else if list.status == 2}}'
						+        							'<li class="item-content">'
						+        								'<div class="item-inner">'
						+        									'<div class="item-title f_999">'
						+        										'{{if is_podcast}}'
						+        											'未收款'
						+        										'{{else}}'
						+        											'未付款'
						+        										'{{/if}}'
						+        									'</div>'
						+        									'<div class="item-after"><span class="diamond f_theme">{{list.pai_diamonds}}</span></div>'
						+        								'</div>'
						+        							'</li>'
						+        						'{{else if list.status == 3}}'
						+        							'<li class="item-content">'
						+        								'<div class="item-inner">'
						+        									'<div class="item-title f_999">'
						+        										'{{if is_podcast}}'
						+        											'未收款'
						+        										'{{else}}'
						+        											'未付款'
						+        										'{{/if}}'
						+        									'</div>'
						+        									'<div class="item-after"><span class="diamond f_theme">{{list.pai_diamonds}}</span></div>'
						+        								'</div>'
						+        							'</li>'
						+        						'{{else if list.status == 4}}'
						+        							'<li class="item-content">'
						+        								'<div class="item-inner">'
						+        									'<div class="item-title f_999">'
						+        										'{{if is_podcast}}'
						+        											'{{if list.order_status == 5}}已退款{{else}}已收款{{/if}}'
						+        										'{{else}}'
						+        											'{{if list.order_status == 5}}已退款{{else if list.order_status == 6 || list.order_status == 0}}未付款{{else}}已付款{{/if}}'
						+        										'{{/if}}'
						+        									'</div>'
						+        									'<div class="item-after"><span class="diamond f_theme">{{list.pai_diamonds}}</span></div>'
						+        								'</div>'
						+        							'</li>'
						+        							'{{if list.order_status < 4}}'
						+        								'<li class="item-content">'
						+        									'<div class="item-inner">'
						+        										'{{if list.order_status == 2}}'
						+        											'<div class="item-title">'
						+        												'{{if list.expire_date_time > 0}}'
						+        													'<span class="f_555 f12">距离约会时间还剩&nbsp;<span class="left_time" data-leftTime="{{list.expire_time}}"></span></span>'
						+        												'{{else}}'
						+        													'{{if is_podcast}}'
						+        														'<span class="f_555 f12">距离确认完成还剩&nbsp;<span class="left_time" data-leftTime="{{list.expire_time}}"></span></span>'
						+        													'{{else}}'
						+        														'<span class="f_555 f12">等待主播确认完成&nbsp;<span class="left_time" data-leftTime="{{list.expire_time}}"></span></span>'
						+        													'{{/if}}'
						+        												'{{/if}}'
						+        											'</div>'
						+        											'{{if list.expire_date_time > 0}}'
						+        												'<div class="item-after">'
						+        													'{{if is_podcast}}'
						+        														'<a href="javascript:void(0);" class="button button-theme button-round button-fill J-remind_buyer_to_date" data-order_sn="{{list.order_sn}}" data-to_buyer_id="{{list.user_id}}">提醒约会</a>'
						+        													'{{else}}'
						+        														'<a href="javascript:void(0);" class="button button-theme button-round button-fill J-remind_podcast_to_date" data-order_sn="{{list.order_sn}}" data-to_podcast_id="{{list.podcast_id}}">提醒约会</a>'
						+        													'{{/if}}'
						+        												'</div>'
						+        											'{{else}}'
						+        												'{{if is_podcast}}'
						+        													'<div class="item-after">'
						+        														'<a href="javascript:void(0);" class="button button-theme button-round button-fill J-confirm_virtual_auction" data-order_sn="{{list.order_sn}}" data-to_buyer_id="{{list.user_id}}">确认完成</a>'
						+        													'</div>'
						+        												'{{/if}}'
						+        											'{{/if}}'
						+        										'{{else if list.order_status == 3}}'
						+        											'{{if is_podcast}}'
						+        												'<div class="item-title"></div>'
						+        												'<div class="item-after">'
						+        													'<a href="javascript:void(0);" class="button button-theme button-round button-fill J-remind_buyer_receive" data-order_sn="{{list.order_sn}}" data-to_buyer_id="{{list.user_id}}">提醒买家</a>'
						+        												'</div>'
						+        											'{{else}}'
						+        												'<div class="item-title">'
						+        													'<span class="f_555 f12">距离确认完成还剩&nbsp;<span class="left_time" data-leftTime="{{list.expire_time}}"></span></span>'
						+        												'</div>'
						+        												'<div class="">'
						+        													'<a href="javascript:void(0);" class="button button-theme button-round button-fill J-buyer_confirm_date" data-order_sn="{{list.order_sn}}" data-to_podcast_id="{{list.podcast_id}}" style="margin-bottom:0.5rem;">确认完成约会</a><a href="javascript:void(0);" class="button button-theme button-round button-fill J-buyer_to_refund" data-order_sn="{{list.order_sn}}" data-to_podcast_id="{{list.podcast_id}}">申请退款</a>'
						+        												'</div>'
						+        											'{{/if}}'
						+        										'{{/if}}'
						+        									'</div>'
						+        								'</li>'
						+        							'{{/if}}'
						+        						'{{/if}}'
						+        					'</ul>'
						+        				'</div>'
						+        			'</div>'
						+        		'</li>'
						+    		 '{{/each}}';

						var render = template.compile(source);
						var html = render({
						    list: data_list,
						    is_podcast: is_podcast
						});
			        	$(".ul-good-virtual").append(html);
			        	// 初始化倒计时
					    $(".left_time").each(function(){
					    	var leftTime = Math.abs(parseInt($(this).attr("data-leftTime")));
					    	left_time(leftTime,$(this));
					    });
		        	}
		        	else{
		        		loading = false;
		        		$.toast(result.error ? result.error : "操作失败");
		        	}
		        	loading = false;
		        	$.refreshScroller();
		        }
	      	});
	    });
	}
});